server:
  port: 8081

spring:
  application:
    name: task-list
  config:
    import: optional:file:.env[.properties]

  cache:
    type: redis
    cache-names: redis-cache

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      continue-on-error: false
  #      data-locations: classpath:demo_data.sql

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
#  jpa:
#    hibernate:
#      ddl-auto: none

  graphql:
    graphiql:
      enabled: true

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true



security:
  jwt:
    secret: ${JWT_SECRET}
    access-duration: ${JWT_ACCESS_DURATION}
    refresh-duration: ${JWT_REFRESH_DURATION}

springdoc:
  override-with-generic-response: false

minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}